# NumPy

* **Numpy analitik anlamda yüksek seviyede vektörel ve nümerik hesaplamalar yapılmasna imkan sağlar.**

In [1]:
import numpy as np

In [2]:
np.array([10, 20, 30, 40, 50])

array([10, 20, 30, 40, 50])

In [4]:
a = np.array([10, 20, 30, 40, 50])
type(a)

numpy.ndarray

**Normal dizilerde her değer için ayrı veri tipi tutulurken numpy ile bu dizinin tamamı tek tipte oluşturulur.** 

In [5]:
np.array([47, 4.8, 9, 134])

array([ 47. ,   4.8,   9. , 134. ])

**Peki bu tipleri biz istegimize gore ayarlayabilir miyiz?**

In [7]:
np.array([47, 4.8, 9, 134], dtype = "int")

array([ 47,   4,   9, 134])

In [8]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.full((3,5), 9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [14]:
np.arange(0, 51, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [12]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
# Ortalaması 10 standart sapması 5 olan 4x4 luk matris

In [18]:
np.random.normal(10, 5, (4,4))

array([[ 3.66315843,  9.50152261,  7.48365633, 11.91377682],
       [ 6.96619025,  4.77295764,  0.81131278, 11.57192885],
       [ 5.11478744,  4.61949128,  9.43014494,  7.07035502],
       [16.06216662, -5.63833095,  8.63541668,  8.18330635]])

In [20]:
np.random.randint(0, 10, (3,3))

array([[4, 2, 4],
       [1, 5, 5],
       [5, 6, 3]])

## NumPy Array Ozellikleri

* **ndim :** boyut sayısı
* **shape :** boyut bilgisi
* **size :** toplam eleman sayısı
* **dtype :** array veri tipi

In [21]:
import numpy as np

In [22]:
a = np.random.randint(10, size = 15)

In [23]:
a.ndim

1

In [24]:
a.shape

(15,)

In [27]:
a.size

15

In [25]:
a.dtype

dtype('int32')

In [28]:
b = np.random.randint(10, size = (3,5))

In [29]:
b.ndim

2

In [30]:
b.shape

(3, 5)

In [31]:
b.size

15

In [32]:
b.dtype

dtype('int32')

## Yeniden Şekillendirme (reshaping)

In [33]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Bir vektörü tek boyut bilgilerini tanıyacak biçimde iki boyutlu matrise çevirelim**

In [36]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a.ndim

1

In [38]:
b = a.reshape((1,9))

In [39]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [40]:
b.ndim

2

## Array Birleştirme (Concatenation)

In [42]:
import numpy as np

In [43]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [44]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [45]:
z = np.array([7, 8, 9])

In [46]:
np.concatenate([x, y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a = np.array([[1, 2, 3,],
              [4, 5, 6]])

In [51]:
np.concatenate([a,a])  # satır bazında birleştirir

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
np.concatenate([a,a], axis = 0)  # satır bazında birleştirir

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([a,a], axis = 1)  # sütun bazında birleştirir

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma İşlemleri (Splitting)

In [54]:
import numpy as np

In [56]:
x = np.array([1, 3, 5, 2, 2, 5, 3, 1])

In [57]:
np.split(x, [3,5])

[array([1, 3, 5]), array([2, 2]), array([5, 3, 1])]

In [58]:
a,b,c = np.split(x, [3,5])

In [59]:
a

array([1, 3, 5])

In [60]:
b

array([2, 2])

In [61]:
c

array([5, 3, 1])

In [62]:
m = np.arange(16).reshape(4,4)

In [63]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [65]:
ust, alt = np.vsplit(m, [2])

In [66]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [67]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [69]:
sag, sol = np.hsplit(m, [2])

In [70]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [71]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama (sorting)

In [72]:
a = np.array([5, 10, 42, 33, 58])

In [73]:
np.sort(a)

array([ 5, 10, 33, 42, 58])

In [75]:
a  # orjinal hali sıralı değil

array([ 5, 10, 42, 33, 58])

In [76]:
a.sort()

In [77]:
a

array([ 5, 10, 33, 42, 58])

In [79]:
m = np.random.normal(10, 5, (3,3))

In [80]:
m

array([[16.11180778, 12.93890418,  8.11852669],
       [ 5.44501577,  3.72327365, 16.48641607],
       [14.12295303, 11.92496049, 10.63928034]])

In [ ]:
# satırları kendi içinde kucukten buyuge olacak sekilde sıralar

In [81]:
np.sort(m, axis = 1) 

array([[ 8.11852669, 12.93890418, 16.11180778],
       [ 3.72327365,  5.44501577, 16.48641607],
       [10.63928034, 11.92496049, 14.12295303]])

In [82]:
# sutunları kendi içinde kucukten buyuge olacak sekilde sıralar

In [83]:
np.sort(m, axis = 0)

array([[ 5.44501577,  3.72327365,  8.11852669],
       [14.12295303, 11.92496049, 10.63928034],
       [16.11180778, 12.93890418, 16.48641607]])

## Kosullu Eleman İslemleri

In [1]:
import numpy as np

In [2]:
v = np.array([10, 20, 30, 40, 50])

In [3]:
v > 30

array([False, False, False,  True,  True])

In [4]:
v[v > 30]

array([40, 50])

In [6]:
v[v == 30]

array([30])

In [8]:
v[v != 30]

array([10, 20, 40, 50])

In [9]:
v**2

array([ 100,  400,  900, 1600, 2500], dtype=int32)

## Matematiksel İşlemler

In [10]:
import numpy as np

In [11]:
v = np.array([10, 20, 30, 40, 50])

In [14]:
np.subtract(v, 5)

array([ 5, 15, 25, 35, 45])

In [15]:
np.add(v, 3)

array([13, 23, 33, 43, 53])

In [16]:
np.multiply(v, 4)

array([ 40,  80, 120, 160, 200])

In [19]:
np.divide(v, 4)

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [20]:
np.power(v, 2)

array([ 100,  400,  900, 1600, 2500], dtype=int32)

In [22]:
np.mod(v, 4)

array([2, 0, 2, 0, 2], dtype=int32)

In [24]:
np.absolute(np.array([-30]))

array([30])

In [25]:
np.sin(360)

0.9589157234143065

In [26]:
np.log2(v)

array([3.32192809, 4.32192809, 4.9068906 , 5.32192809, 5.64385619])

## İstatistiksel Hesaplamalar

In [27]:
v = np.array([10, 20, 30, 40, 50])

In [28]:
v.mean()

30.0

In [29]:
v.sum()

150

In [30]:
v.min()

10

In [31]:
v.max()

50

In [33]:
v.std()

14.142135623730951

In [34]:
np.std(v, axis = 0)

14.142135623730951

## Numpy ile İki Bilinmeyenli Denklem Çözümü

In [35]:
import numpy as np

**10 * x0 + x1 = 24**

**x0 + 6 * x1 = 20**

In [37]:
a = np.array([[10,1], [1,6]])
b = np.array([24,20])

In [38]:
x = np.linalg.solve(a, b)

In [40]:
x    # (x0 ve x1 hesaplandı)

array([2.10169492, 2.98305085])